CREATE TABLE S_NOTICE_BOARD 
(
  N_ID NUMBER NOT NULL 
, N_SUBJECT VARCHAR2(250 BYTE) 
, N_CONTENT VARCHAR2(4000 BYTE) 
, N_PUBLISH_DATE DATE 
, N_PUBLISH_BY VARCHAR2(20 BYTE) 
, CONSTRAINT S_NOTICE_BOARD_PK PRIMARY KEY 
  (
    N_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_NOTICE_BOARD_PK ON S_NOTICE_BOARD (N_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
